server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Forever-nuo/cloudConfig.git
          username: 857173891@qq.com
          password: devil857nuo

