server:
  port: 9527

spring:
#################################应用相关配置##################################################
  application:
    name: microservicecloud-zuul-gateway #微服务的暴露的名称

eureka:
  client:
    service-url:
      defaultZone : http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

info:
  app.name : forever-microservicecloud
  company.name : www.forever.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
